spring.application.name=CapStone-Prodigy

security.jwt.secret-key=ajkbdjhvaoybfvlkjabfviuypaigjsfbvjagvweoucypqijdbvkevjpiwuygiadhbjhsvcoauwyegcoahbsdljhvpiudghhsdbvjherbvauygrvouahsbvcjkaghgdvouaicbaljfhvclahsfgvohcblvav

security.jwt.expiration-time=360000

hardcoded.username = admin

hardcoded.password = admin123